# -*- coding: utf-8 -*-
"""map_filter_reduce_lambda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eb8tV0cKc7RwbpcmvGtIjQTWD-k60AC2

## Using lambda with Built-in Functions

# map(function, iterable)
"""

lst = [2,5,8,9]

squared = list(map(lambda x: x**2, lst))

print(squared)

"""# filter(function, iterable)"""

fil_squared = list(filter(lambda x: x%2==0, lst))

print(fil_squared)

"""# reduce(function, iterable)"""

from functools import reduce
sum_all = reduce(lambda x, y: x + y, lst)
print(sum_all)

"""## Lambda in pandas"""

import pandas as pd

df = pd.DataFrame({'a': [1, 2, 3], 'b': [10, 20, 30]})

df['sum'] = df.apply(lambda row: row['a'] + row['b'], axis=1)

print(df)

df['label'] = df['a'].apply(lambda x: 'High' if x > 1 else 'Low')

print(df)

grouped_mean = df.groupby('label')['b'].apply(lambda x: x.mean())

print(grouped_mean)

